"use client";

import {
  CircleCheckIcon,
  InfoIcon,
  Loader2Icon,
  OctagonXIcon,
  TriangleAlertIcon,
} from "lucide-react";
import { Toaster as Sonner, type ToasterProps } from "sonner";
import { useTheme } from "@/components/theme-provider";

/*
 * Generated by shadcn and then narrowed by hand, which is the arrangement
 * shadcn intends: the component lives in this repository and belongs to it.
 *
 * The change is one line. `useTheme()` types its value as possibly undefined,
 * and this project compiles with `exactOptionalPropertyTypes`, under which
 * passing `undefined` to an optional prop is an error rather than the same as
 * omitting it. Resolving the fallback before it reaches the prop keeps the
 * strictness — which is worth more here than the two characters it costs — and
 * makes the default explicit rather than implied.
 */
const Toaster = ({ ...props }: ToasterProps) => {
  const { theme } = useTheme();
  const resolved: NonNullable<ToasterProps["theme"]> =
    theme === "light" || theme === "dark" ? theme : "system";

  return (
    <Sonner
      theme={resolved}
      className="toaster group"
      icons={{
        success: <CircleCheckIcon className="size-4" />,
        info: <InfoIcon className="size-4" />,
        warning: <TriangleAlertIcon className="size-4" />,
        error: <OctagonXIcon className="size-4" />,
        loading: <Loader2Icon className="size-4 animate-spin" />,
      }}
      style={
        {
          "--normal-bg": "var(--popover)",
          "--normal-text": "var(--popover-foreground)",
          "--normal-border": "var(--border)",
          "--border-radius": "var(--radius)",
        } as React.CSSProperties
      }
      toastOptions={{
        classNames: {
          toast: "cn-toast",
        },
      }}
      {...props}
    />
  );
};

export { Toaster };
